debug: true

spring:
  aop:
    proxy-target-class: true

security:
  user:
    password: password
  oauth2:
    client:
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientId: 1041144924884-pl71kgmha80janlnkdvr8ocnb9ptoibd.apps.googleusercontent.com
      clientSecret: arNBTNWpbQ6OU6xmvNTPJhF8
      scope: "profile email"
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
    user:
      path: /user/**
      url: https://www.googleapis.com/oauth2/v2/userinfo

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG